// AUTO-GENERATED by scripts/gen-license-key.mjs — НЕ редактировать руками.
// Только ПУБЛИЧНЫЙ ключ. Безопасно коммитить: им нельзя подделать код.
export const LICENSE_PUBLIC_KEY_JWK = {"kty":"EC","crv":"P-256","x":"VC96VEFuXNJ32mYN4vUQfyVsWkBObRimWaTZkgW8zwY","y":"YmT3VvBPvEopkDYAE4UGODCIAg6OD4cUquw3OizgIrI"} as const;
